use crate::dag::{
    ChainKey, EncryptionKey, EphemeralX25519Pk, EphemeralX25519Sk, HeaderKey, KConv, MacKey,
    MessageKey, NodeMac, PhysicalDevicePk, PhysicalDeviceSk, SenderKey, SharedSecretKey,
};
use blake3::derive_key;
use chacha20::ChaCha20;
use chacha20::cipher::{KeyIvInit, StreamCipher};
use curve25519_dalek::edwards::CompressedEdwardsY;
use sha2::{Digest, Sha512};
use subtle::ConstantTimeEq;
use x25519_dalek::{PublicKey as XPublicKey, StaticSecret};
use zeroize::Zeroize;

/// Keys to pack content node into wire format.
pub struct PackContentKeys {
    pub k_msg: MessageKey,       // payload encryption + sender_hint
    pub k_header: HeaderKey,     // routing AEAD
    pub routing_nonce: [u8; 12], // random, generated by caller
    pub payload_nonce: [u8; 12], // random, generated by caller
}

/// Keys for packing MerkleNode into WireNode.
pub enum PackKeys {
    /// Content nodes: encrypted routing + payload.
    Content(PackContentKeys),
    /// Admin, KeyWrap, HistoryExport, SKD: cleartext.
    Exception,
}

/// K_header_epoch_n = Blake3-KDF("merkle-tox v1 header-key", K_conv || SenderKey_n)
pub fn derive_k_header_epoch(k_conv: &KConv, sender_key_n: &SenderKey) -> HeaderKey {
    let mut material = [0u8; 64];
    material[0..32].copy_from_slice(k_conv.as_bytes());
    material[32..64].copy_from_slice(sender_key_n.as_bytes());
    let result = HeaderKey::from(derive_key("merkle-tox v1 header-key", &material));
    material.zeroize();
    result
}

/// sender_hint = Blake3-KDF("merkle-tox v1 hint", K_msg)[0..4]
pub fn compute_sender_hint(k_msg: &MessageKey) -> [u8; 4] {
    let full = derive_key("merkle-tox v1 hint", k_msg.as_bytes());
    let mut hint = [0u8; 4];
    hint.copy_from_slice(&full[0..4]);
    hint
}

/// AEAD-encrypts routing data (sequence number) under K_header.
/// Returns 24 bytes: 8 bytes ciphertext + 16 bytes Poly1305 tag.
/// Caller prepends nonce externally.
pub fn encrypt_routing_aead(
    k_header: &HeaderKey,
    nonce: &[u8; 12],
    seq: u64,
    aad: &[u8; 32],
) -> Vec<u8> {
    use chacha20poly1305::ChaCha20Poly1305;
    use chacha20poly1305::aead::{AeadInPlace, KeyInit};

    let cipher = ChaCha20Poly1305::new(k_header.as_bytes().into());
    let plaintext = seq.to_be_bytes();
    let mut buffer = plaintext.to_vec();
    let tag = cipher
        .encrypt_in_place_detached(nonce.into(), aad, &mut buffer)
        .expect("AEAD encrypt should not fail");
    buffer.extend_from_slice(&tag);
    buffer
}

/// AEAD-decrypts routing data. Returns sequence number on success.
pub fn decrypt_routing_aead(
    k_header: &HeaderKey,
    nonce: &[u8; 12],
    ciphertext: &[u8],
    aad: &[u8; 32],
) -> Option<u64> {
    use chacha20poly1305::ChaCha20Poly1305;
    use chacha20poly1305::aead::{AeadInPlace, KeyInit};

    if ciphertext.len() != 24 {
        return None;
    }

    let cipher = ChaCha20Poly1305::new(k_header.as_bytes().into());
    let (ct, tag_bytes) = ciphertext.split_at(8);
    let mut buffer = ct.to_vec();
    let tag = chacha20poly1305::Tag::from_slice(tag_bytes);
    cipher
        .decrypt_in_place_detached(nonce.into(), aad, &mut buffer, tag)
        .ok()?;
    let seq = u64::from_be_bytes(buffer.try_into().ok()?);
    Some(seq)
}

#[derive(Clone, Zeroize)]
pub struct ConversationKeys {
    pub k_conv: KConv,
    pub k_enc: EncryptionKey,
    pub k_mac: MacKey,
}

/// Converts Ed25519 public key to X25519 public key via birational map.
/// Returns `None` if bytes are not valid compressed Edwards Y coordinate
/// (e.g., when key is already X25519/Montgomery key).
pub fn ed25519_pk_to_x25519(ed_pk: &[u8; 32]) -> Option<XPublicKey> {
    let ed_point = CompressedEdwardsY(*ed_pk).decompress()?;
    let x_bytes = ed_point.to_montgomery().0;
    Some(XPublicKey::from(x_bytes))
}

/// Converts device public key to X25519.
///
/// Applies standard birational Edwards to Montgomery map for Ed25519 keys.
/// Uses bytes directly for native X25519 keys (e.g., Tox DHT keys).
pub fn device_pk_to_x25519(pk: &[u8; 32]) -> XPublicKey {
    ed25519_pk_to_x25519(pk).unwrap_or_else(|| XPublicKey::from(*pk))
}

/// Derives Ed25519 public key from 32-byte seed.
///
/// Treats Tox X25519 secret key as Ed25519 seed to derive MerkleTox protocol identity.
pub fn ed25519_public_key_from_seed(seed: &[u8; 32]) -> [u8; 32] {
    use ed25519_dalek::SigningKey;
    SigningKey::from_bytes(seed).verifying_key().to_bytes()
}

/// Converts Ed25519 secret seed to X25519 secret key (scalar).
/// Follows standard RFC 8032 and libsodium conversion.
pub fn ed25519_sk_to_x25519(ed_sk: &[u8; 32]) -> [u8; 32] {
    let mut hasher = Sha512::new();
    hasher.update(ed_sk);
    let mut hash = hasher.finalize();
    let mut x_sk = [0u8; 32];
    x_sk.copy_from_slice(&hash[0..32]);
    hash.as_mut_slice().zeroize();

    // Clamping
    x_sk[0] &= 248;
    x_sk[31] &= 127;
    x_sk[31] |= 64;

    x_sk
}

/// ECIES wrap: DH(ephemeral_sk, recipient_spk) to KDF to ChaCha20-Poly1305.
/// Returns ciphertext (plaintext.len() + 16 tag bytes).
pub fn ecies_wrap(
    ephemeral_sk: &EphemeralX25519Sk,
    recipient_spk: &EphemeralX25519Pk,
    recipient_opk: Option<&EphemeralX25519Pk>,
    auth_secret: Option<&[u8; 32]>,
    plaintext: &[u8],
) -> Vec<u8> {
    use chacha20poly1305::ChaCha20Poly1305;
    use chacha20poly1305::aead::{Aead, KeyInit};

    let e = StaticSecret::from(*ephemeral_sk.as_bytes());
    let spk = XPublicKey::from(*recipient_spk.as_bytes());
    let shared_spk = e.diffie_hellman(&spk);

    let mut material = Vec::with_capacity(96);
    material.extend_from_slice(shared_spk.as_bytes());
    if let Some(opk) = recipient_opk {
        let opk_pub = XPublicKey::from(*opk.as_bytes());
        material.extend_from_slice(e.diffie_hellman(&opk_pub).as_bytes());
    }
    if let Some(auth) = auth_secret {
        material.extend_from_slice(auth);
    }

    let mut k_wrap = derive_key("merkle-tox v1 keywrap", &material);
    material.zeroize();
    // ChaCha20-Poly1305 with zero nonce (safe: key is unique per entry)
    let cipher = ChaCha20Poly1305::new(&k_wrap.into());
    k_wrap.zeroize();
    cipher
        .encrypt(&[0u8; 12].into(), plaintext.as_ref())
        .expect("ECIES wrap should not fail")
}

/// ECIES unwrap: DH(self_spk_sk, ephemeral_pk) to KDF to ChaCha20-Poly1305.
/// Returns variable-length plaintext or None on auth tag failure.
pub fn ecies_unwrap(
    self_spk_sk: &EphemeralX25519Sk,
    ephemeral_pk: &EphemeralX25519Pk,
    self_opk_sk: Option<&EphemeralX25519Sk>,
    auth_secret: Option<&[u8; 32]>,
    ciphertext: &[u8],
) -> Option<Vec<u8>> {
    use chacha20poly1305::ChaCha20Poly1305;
    use chacha20poly1305::aead::{Aead, KeyInit};

    if ciphertext.len() < 16 {
        return None;
    }

    let spk = StaticSecret::from(*self_spk_sk.as_bytes());
    let e_pub = XPublicKey::from(*ephemeral_pk.as_bytes());
    let shared_spk = spk.diffie_hellman(&e_pub);

    let mut material = Vec::with_capacity(96);
    material.extend_from_slice(shared_spk.as_bytes());
    if let Some(opk_sk) = self_opk_sk {
        let opk = StaticSecret::from(*opk_sk.as_bytes());
        material.extend_from_slice(opk.diffie_hellman(&e_pub).as_bytes());
    }
    if let Some(auth) = auth_secret {
        material.extend_from_slice(auth);
    }

    let mut k_wrap = derive_key("merkle-tox v1 keywrap", &material);
    material.zeroize();
    let cipher = ChaCha20Poly1305::new(&k_wrap.into());
    k_wrap.zeroize();
    cipher.decrypt(&[0u8; 12].into(), ciphertext).ok()
}

/// ECIES unwrap wrapper for 32-byte payloads.
/// Returns exactly 32 bytes or None.
pub fn ecies_unwrap_32(
    self_spk_sk: &EphemeralX25519Sk,
    ephemeral_pk: &EphemeralX25519Pk,
    self_opk_sk: Option<&EphemeralX25519Sk>,
    auth_secret: Option<&[u8; 32]>,
    ciphertext: &[u8],
) -> Option<[u8; 32]> {
    let pt = ecies_unwrap(
        self_spk_sk,
        ephemeral_pk,
        self_opk_sk,
        auth_secret,
        ciphertext,
    )?;
    if pt.len() != 32 {
        return None;
    }
    let mut out = [0u8; 32];
    out.copy_from_slice(&pt);
    Some(out)
}

impl ConversationKeys {
    pub fn derive(k_conv: &KConv) -> Self {
        let k_enc = derive_key("merkle-tox v1 enc", k_conv.as_bytes());
        let k_mac = derive_key("merkle-tox v1 mac", k_conv.as_bytes());
        tracing::debug!(
            "Derived keys from {}: k_mac={}",
            hex::encode(k_conv.as_bytes()),
            hex::encode(k_mac)
        );
        Self {
            k_conv: k_conv.clone(),
            k_enc: EncryptionKey::from(k_enc),
            k_mac: MacKey::from(k_mac),
        }
    }

    pub fn calculate_mac(&self, data: &[u8]) -> NodeMac {
        tracing::debug!(
            "Calculating MAC with k_mac: {}",
            hex::encode(self.k_mac.as_bytes())
        );
        tracing::debug!(
            "  Data prefix: {}",
            hex::encode(&data[..std::cmp::min(data.len(), 16)])
        );
        NodeMac::from(*blake3::keyed_hash(self.k_mac.as_bytes(), data).as_bytes())
    }

    pub fn verify_mac(&self, data: &[u8], mac: &NodeMac) -> bool {
        let calculated = self.calculate_mac(data);
        let res: bool = calculated.as_bytes().ct_eq(mac.as_bytes()).into();
        if !res {
            tracing::debug!(
                "MAC verification failed with k_mac prefix: {}",
                hex::encode(&self.k_mac.as_bytes()[..8])
            );
            tracing::debug!("  Calculated:  {:?}", calculated.as_bytes());
            tracing::debug!("  Expected:    {:?}", mac.as_bytes());
            tracing::debug!("  Data len:    {}", data.len());
            tracing::debug!("  Data hex:    {}", hex::encode(data));
        }
        res
    }

    /// Encrypts data using ChaCha20.
    /// Nonce derives from node hash, topological rank, or provided externally.
    /// WireNode obfuscation uses first 12 bytes of first parent hash as nonce, or zero nonce if Genesis.
    pub fn encrypt(&self, nonce: &[u8; 12], data: &mut [u8]) {
        let mut cipher = ChaCha20::new(self.k_enc.as_bytes().into(), nonce.into());
        cipher.apply_keystream(data);
    }

    /// Decrypts data using ChaCha20.
    pub fn decrypt(&self, nonce: &[u8; 12], data: &mut [u8]) {
        self.encrypt(nonce, data); // ChaCha20 is symmetric
    }

    /// Decrypts node payload using nonce derived from MAC.
    pub fn decrypt_payload_with_mac(&self, mac: &NodeMac, data: &mut [u8]) {
        let mut nonce = [0u8; 12];
        nonce.copy_from_slice(&mac.as_bytes()[0..12]);
        self.decrypt(&nonce, data);
    }

    /// Encrypts node payload using nonce derived from MAC.
    pub fn encrypt_payload_with_mac(&self, mac: &NodeMac, data: &mut [u8]) {
        let mut nonce = [0u8; 12];
        nonce.copy_from_slice(&mac.as_bytes()[0..12]);
        self.encrypt(&nonce, data);
    }
}

/// Computes X3DH shared secret for initiator.
pub fn x3dh_derive_secret_initiator(
    self_device_sk: &PhysicalDeviceSk,
    self_ephemeral_sk: &EphemeralX25519Sk,
    peer_device_pk: &PhysicalDevicePk,
    peer_signed_pre_pk: &EphemeralX25519Pk,
    peer_one_time_pk: Option<&EphemeralX25519Pk>,
) -> Option<SharedSecretKey> {
    use x25519_dalek::{PublicKey as XPublicKey, StaticSecret};

    let i_a = StaticSecret::from(ed25519_sk_to_x25519(self_device_sk.as_bytes()));
    let e_a = StaticSecret::from(*self_ephemeral_sk.as_bytes());

    let i_b = ed25519_pk_to_x25519(peer_device_pk.as_bytes())?;
    let spk_b = XPublicKey::from(*peer_signed_pre_pk.as_bytes());

    let dh1 = i_a.diffie_hellman(&spk_b);
    let dh2 = e_a.diffie_hellman(&i_b);
    let dh3 = e_a.diffie_hellman(&spk_b);

    let mut material = Vec::with_capacity(32 * 4);
    material.extend_from_slice(dh1.as_bytes());
    material.extend_from_slice(dh2.as_bytes());
    material.extend_from_slice(dh3.as_bytes());

    if let Some(opk_b_pk) = peer_one_time_pk {
        let opk_b = XPublicKey::from(*opk_b_pk.as_bytes());
        let dh4 = e_a.diffie_hellman(&opk_b);
        material.extend_from_slice(dh4.as_bytes());
    }

    let result = SharedSecretKey::from(derive_key("merkle-tox v1 x3dh-shared", &material));
    material.zeroize();
    Some(result)
}

/// Computes X3DH shared secret for recipient.
pub fn x3dh_derive_secret_recipient(
    self_device_sk: &PhysicalDeviceSk,
    self_signed_pre_sk: &EphemeralX25519Sk,
    peer_device_pk: &PhysicalDevicePk,
    peer_ephemeral_pk: &EphemeralX25519Pk,
    self_one_time_sk: Option<&EphemeralX25519Sk>,
) -> Option<SharedSecretKey> {
    use x25519_dalek::{PublicKey as XPublicKey, StaticSecret};

    let i_b = StaticSecret::from(ed25519_sk_to_x25519(self_device_sk.as_bytes()));
    let spk_b = StaticSecret::from(*self_signed_pre_sk.as_bytes());

    let i_a = ed25519_pk_to_x25519(peer_device_pk.as_bytes())?;
    let e_a = XPublicKey::from(*peer_ephemeral_pk.as_bytes());

    let dh1 = spk_b.diffie_hellman(&i_a);
    let dh2 = i_b.diffie_hellman(&e_a);
    let dh3 = spk_b.diffie_hellman(&e_a);

    let mut material = Vec::with_capacity(32 * 4);
    material.extend_from_slice(dh1.as_bytes());
    material.extend_from_slice(dh2.as_bytes());
    material.extend_from_slice(dh3.as_bytes());

    if let Some(opk_b_sk) = self_one_time_sk {
        let opk_b_sk = StaticSecret::from(*opk_b_sk.as_bytes());
        let dh4 = opk_b_sk.diffie_hellman(&e_a);
        material.extend_from_slice(dh4.as_bytes());
    }

    let result = SharedSecretKey::from(derive_key("merkle-tox v1 x3dh-shared", &material));
    material.zeroize();
    Some(result)
}

/// Initializes ratchet chain key for sender from conversation key.
pub fn ratchet_init_sender(k_conv: &KConv, sender_pk: &PhysicalDevicePk) -> ChainKey {
    let mut material = [0u8; 64];
    material[0..32].copy_from_slice(k_conv.as_bytes());
    material[32..64].copy_from_slice(sender_pk.as_bytes());
    let result = ChainKey::from(derive_key("merkle-tox v1 sender-seed", &material));
    material.zeroize();
    result
}

/// Derives next chain key from current.
pub fn ratchet_step(chain_key: &ChainKey) -> ChainKey {
    ChainKey::from(derive_key(
        "merkle-tox v1 ratchet-step",
        chain_key.as_bytes(),
    ))
}

/// Derives message encryption key from chain key.
pub fn ratchet_message_key(chain_key: &ChainKey) -> MessageKey {
    MessageKey::from(derive_key(
        "merkle-tox v1 message-key",
        chain_key.as_bytes(),
    ))
}

/// Derives K_iblt from conversation key and ID.
/// Keyed hash prevents external parties without K_conv from crafting valid IBLT sketches to poison reconciliation.
pub fn derive_k_iblt(k_conv: &KConv, conversation_id: &crate::dag::ConversationId) -> [u8; 32] {
    let mut material = [0u8; 64];
    material[0..32].copy_from_slice(k_conv.as_bytes());
    material[32..64].copy_from_slice(conversation_id.as_bytes());
    let result = derive_key("merkle-tox v1 iblt-conv-key", &material);
    material.zeroize();
    result
}

/// Derives K_header_export from K_conv for HistoryExport room-wide encryption.
pub fn derive_k_header_export(k_conv: &KConv) -> HeaderKey {
    HeaderKey::from(derive_key("merkle-tox v1 header-export", k_conv.as_bytes()))
}

/// Derives K_payload_export from K_conv for HistoryExport room-wide encryption.
pub fn derive_k_payload_export(k_conv: &KConv) -> EncryptionKey {
    EncryptionKey::from(derive_key(
        "merkle-tox v1 payload-export",
        k_conv.as_bytes(),
    ))
}

/// Derives deterministic dedup_id for LegacyBridge nodes.
/// dedup_id = blake3::hash(conversation_id || source_pk || text_length(u32-BE) || text || message_type)
pub fn derive_legacy_bridge_dedup_id(
    conversation_id: &crate::dag::ConversationId,
    source_pk: &PhysicalDevicePk,
    text: &str,
    message_type: u8,
) -> crate::dag::NodeHash {
    let mut hasher = blake3::Hasher::new();
    hasher.update(conversation_id.as_bytes());
    hasher.update(source_pk.as_bytes());
    hasher.update(&(text.len() as u32).to_be_bytes());
    hasher.update(text.as_bytes());
    hasher.update(&[message_type]);
    crate::dag::NodeHash::from(*hasher.finalize().as_bytes())
}
